# This rule is not used by the project kubuild itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubuild.lingdie.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubuild
    app.kubernetes.io/managed-by: kustomize
  name: buildtask-admin-role
rules:
- apiGroups:
  - kubuild.lingdie.io
  resources:
  - buildtasks
  verbs:
  - '*'
- apiGroups:
  - kubuild.lingdie.io
  resources:
  - buildtasks/status
  verbs:
  - get
